stages:
  - mavenbuild
  - maventest
  - mavendeploy
  - androidbuild
  - androidtest

maven-build:
  stage: mavenbuild
  tags:
    - main_backend
  script:
    # 1) Forzar Java 17 para este job
    - export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-17.0.17.0.10-1.el9.x86_64
    - export PATH="$JAVA_HOME/bin:$PATH"
    - java -version
    - mvn -v

    # 2) Build del backend
    - cd Backend/backend_code
    - mvn package
  artifacts:
    paths:
      - Backend/backend_code/target/*.jar
  only:
    refs:
      - main
    changes:
      - Backend/backend_code/**/*

maven-test:
  stage: maventest
  tags:
    - main_backend
  script:
    - export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-17.0.17.0.10-1.el9.x86_64
    - export PATH="$JAVA_HOME/bin:$PATH"
    - java -version
    - mvn -v

    - cd Backend/backend_code
    - mvn test
  only:
    refs:
      - main
    changes:
      - Backend/backend_code/**/*

auto-deploy:
  stage: mavendeploy
  tags:
    - main_backend      # Updated to your registered runner tag
    - shell
  script:
    - cd Backend/backend_code
    - sudo mv target/*.jar /target/web-demo.jar
    - sudo systemctl stop system-web-demo
    - sudo systemctl start system-web-demo
  only:
    refs:
      - main
    changes:
      - Backend/backend_code/**/*

android-build:
  image: afirefly/android-ci:java17
  stage: androidbuild
  tags:
    - main_frontend     # Updated to your registered runner tag
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./Frontend/CyMarket/gradlew
  script:
    - cd Frontend/CyMarket
    - ./gradlew build
  only:
    refs:
      - main
    changes:
      - Frontend/CyMarket/**/*

android-test:
  image: afirefly/android-ci:java17
  stage: androidtest
  tags:
    - main_frontend     # Updated to your registered runner tag
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./Frontend/CyMarket/gradlew
  script:
    - cd Frontend/CyMarket
    - ./gradlew test
  only:
    refs:
      - main
    changes:
      - Frontend/CyMarket/**/*
